### ISSUE TITLE
transparent background

### ISSUE THREAD

**Issue by isasaurio** [Dandarawy/Unity3DBookPageCurl#1]
Hello
First thank you very much for your book has helped me a lot .
I have a problem
By putting a transparent image as " backgound " in the book I get the following error.
(Attachment screen)
![boor error](https://cloud.githubusercontent.com/assets/10709329/16645226/7a0e73ce-43f0-11e6-990f-360b6fd1c82f.png)

As we have to do to see the bottom without problems ?

regards

**Comment by Dandarawy** [comment]
Which part should be transparent ?!

**Comment by isasaurio** [comment]
My idea is that the beginning and end of flipping through the book, you can see the background texture.
![error book](https://cloud.githubusercontent.com/assets/10709329/16653354/56dcb1c6-441e-11e6-8b6f-e861be550363.jpg)

**Comment by Dandarawy** [comment]
transparent background should work with you, Just replace this white image with a transparent/semi-transparent image.
I tried it out and it works without any problems.
check the following images, is that what you want?.

![transparentbackground2](https://cloud.githubusercontent.com/assets/7468107/16657313/5555d604-4462-11e6-8c2d-14436f4ac53a.png)

**Comment by Dandarawy** [comment]
I got it, transparent background works but it has a bug, when the background is transparent and you start dragging the first page left to right, the left page will be shown behind the transparent background till the end of flipping.

**Comment by isasaurio** [comment]
Thanks!
Work Perfect !!!!

**Comment by isasaurio** [comment]
I found another error.
![book error 2](https://cloud.githubusercontent.com/assets/10709329/16706633/becd4926-4581-11e6-904a-0654e5be92a2.gif)
 :(

**Comment by Dandarawy** [comment]
That's because the Clipping Mask pivot does not set correctly, sorry I changed the numbers before pushing without test, I'll Update it now.

**Comment by Dandarawy** [comment]
FIXED

**Comment by isasaurio** [comment]
Searching :)


2016-07-09 4:00 GMT-04:00 Dandarawy <notifications@github.com>:

> FIXED
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Dandarawy/Unity3DBookPageCurl/issues/1#issuecomment-231522071>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AKNpUf6R2pNFf4c-AuCx9LAYtgeMVYLNks5qT1U1gaJpZM4JGzJG>
> .
>



-- 


*Isaías Molinet Ramirez Comunicador Multimedia*

*Diseño Web, edici*ó*n de video, Animaci*ó*n 2d, 3d y Fx *y Juegos.
*www.youtube.com/isasaurio <http://www.youtube.com/isasaurio>  *
www.vimeo.com/channels/isasaurio/ <http://vimeo.com/channels/isasaurio/>
*T: 09 2414774*

*"Animando mi propia vida"*

**Comment by Dandarawy** [comment]
Please consider writing a review on the asset store, I'll appreciate it
alot.


BR,

**Comment by isasaurio** [comment]
Hello, if I did already , thank you very much for everything :)


2016-07-09 8:34 GMT-04:00 Dandarawy <notifications@github.com>:

> Please consider writing a review on the asset store, I'll appreciate it
> alot.
>
>
> BR,
>
> On Sat, Jul 9, 2016 at 2:18 PM, isasaurio <notifications@github.com>
> wrote:
>
> > Searching :)
> >
> >
> > 2016-07-09 4:00 GMT-04:00 Dandarawy <notifications@github.com>:
> >
> > > FIXED
> > >
> > > —
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly, view it on GitHub
> > > <
> >
> https://github.com/Dandarawy/Unity3DBookPageCurl/issues/1#issuecomment-231522071
> > >,
> > > or mute the thread
> > > <
> >
> https://github.com/notifications/unsubscribe/AKNpUf6R2pNFf4c-AuCx9LAYtgeMVYLNks5qT1U1gaJpZM4JGzJG
> > >
> > > .
> > >
> >
> >
> >
> > --
> >
> >
> > *Isaías Molinet Ramirez Comunicador Multimedia*
> >
> > *Diseño Web, edici*ó*n de video, Animaci*ó*n 2d, 3d y Fx *y Juegos.
> > *www.youtube.com/isasaurio <http://www.youtube.com/isasaurio> *
> > www.vimeo.com/channels/isasaurio/ <http://vimeo.com/channels/isasaurio/>
> > *T: 09 2414774*
> >
> > *"Animando mi propia vida"*
> >
> > —
> > You are receiving this because you modified the open/close state.
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/Dandarawy/Unity3DBookPageCurl/issues/1#issuecomment-231531700
> >,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe/AHH0SxXLxp6pAwCd9va8iL0bpOMHSs3Vks5qT5GKgaJpZM4JGzJG
> >
> > .
>
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Dandarawy/Unity3DBookPageCurl/issues/1#issuecomment-231532350>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AKNpUeLtcHq8hSWyrmiTDVxJSjjvaT1Eks5qT5VjgaJpZM4JGzJG>
> .
>



-- 


*Isaías Molinet Ramirez Comunicador Multimedia*

*Diseño Web, edici*ó*n de video, Animaci*ó*n 2d, 3d y Fx *y Juegos.
*www.youtube.com/isasaurio <http://www.youtube.com/isasaurio>  *
www.vimeo.com/channels/isasaurio/ <http://vimeo.com/channels/isasaurio/>
*T: 09 2414774*

*"Animando mi propia vida"*

**Comment by Dandarawy** [comment]
you are welcome :)

**Comment by isasaurio** [comment]
Hello friends
I found another error.
I can not put more than 10 images, and I have a book that has 70 :(
By putting more than 10 images , when browsing the latest , it becomes
transparent.

Deputy mistake of screen and print .

How can i fix this?

Thank you very much!!!

![frame error](https://cloud.githubusercontent.com/assets/10709329/17015567/cd0e4a96-4ef8-11e6-8898-d2e121610e79.gif)
![error_book2](https://cloud.githubusercontent.com/assets/10709329/17015572/cf99c6a0-4ef8-11e6-88c9-0e272e610084.gif)

2016-07-11 19:04 GMT-04:00 Dandarawy notifications@github.com:

> you are welcome :)
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/Dandarawy/Unity3DBookPageCurl/issues/1#issuecomment-231891682,
> or mute the thread
> https://github.com/notifications/unsubscribe/AKNpUSQK9FTSNYYX0q11P1CDvoe0P3EHks5qUswSgaJpZM4JGzJG
> .

## 

_Isaías Molinet Ramirez Comunicador Multimedia_

_Diseño Web, edici_ó_n de video, Animaci_ó_n 2d, 3d y Fx *y Juegos.
*www.youtube.com/isasaurio http://www.youtube.com/isasaurio  *
www.vimeo.com/channels/isasaurio/ http://vimeo.com/channels/isasaurio/
*T: 09 2414774_

_"Animando mi propia vida"_

**Comment by Dandarawy** [comment]
Hi,

I added more than 10 pages but didn't notice any problem. can you please
send me a gif to illustrate what happened?!

**Comment by isasaurio** [comment]
hello
this is te problem
![error_book2](https://cloud.githubusercontent.com/assets/10709329/17021339/6187710e-4f15-11e6-898a-4b1f7b05dc87.gif)

![frame error](https://cloud.githubusercontent.com/assets/10709329/17021349/6df539f8-4f15-11e6-8d46-689bc524a8e0.gif)

**Comment by Dandarawy** [comment]
Ok, its not a big problem. This book required an even number of pages, so you can't add 11 pages it must be 10 or 12

**Comment by isasaurio** [comment]
Ok I understand , but how can I do if the book has 11 or 21 or 17 pages ? how you could fix that , some trick?

**Comment by Dandarawy** [comment]
Actually its illogical to have an odd number of pages, you always should have 2 pages for each paper (its front and back) even for the cover, so I didn't try to solve the issue of having odd number because it will lead to a very strange book that has a paper with front and no back.

If you think this does not make sense, think in the simplest possible book; the book have only  a cover, so you have Left cover and right cover each cover has its front page and back page which lead to 4 pages. For each paper that you will add in the book, you should add two pages one for the paper front and one for the paper back, so that the number of pages should always be even number.
