### ISSUE TITLE
Flip The GameObject With Child

### ISSUE THREAD

**Issue by DennzLiu** [Dandarawy/Unity3DBookPageCurl#2]
Hi Dandarawy,

I am Dennis. I have see your Unity Book Page Curl. It is amazing. It is best and FREE too. If i can have a favor ?
How to flip the gameobject with child inside ? 
In your Book Page Curl you have flip the image sprite. What if it is a gameobject ? So we are able to making a process with gameobject for example : 
Page _1 => Gameobject Image With Child => Button, Text, Prefab.
Page _2 => Gameobject Image With Child => Button, Text, Prefab.
and soon.

If we make it a gameobject we are able to making a process like click the button and do process, change text paramater. If it is just image we will not able to do a script.

I am creating a game and planning to make a menu Book. So when the book is open it is contain a ingredient with slot process inside the book.

Is it possible With your Book Page Curl ? If it is Could you give an example ?

You can email me at d.y_liu@yahoo.com.

You help is a great for me to continue the game.
Thanks
Dennis

**Comment by Dandarawy** [comment]
Hi Dennis,

Actually I got a lot of requests for this feature and I'm willing to add it, but now I don't have enough time to work on it

Thanks

**Comment by phatal** [comment]
temporary solution which I use in my project it,s runtime sprites creating. Just render texture2d of your pages at scene start and setting them when you need curl animate. Better then nothing.

**Comment by Dandarawy** [comment]
This feature is supported now on the pro version of the asset you can get it from the asset store: http://u3d.as/ECT
