### ISSUE TITLE
Error adding prefab to my project

### ISSUE THREAD

**Issue by sebasgmas2705** [Dandarawy/Unity3DBookPageCurl#3]
Hello, 
Thank you so much for your work. I was wondering if you could help me. 
When I add the prefab given in the asset, I doesnt work properly. Take a look to this video to see what is happening: https://www.youtube.com/watch?v=7UL8xIucNbs
Could you help me fix this?
Thank you so much

**Comment by Dandarawy** [comment]
make sure that the canvas is in "Screen Space - Overlay", this asset does not work in "Screen Space - Camera"

**Comment by sebasgmas** [comment]
Thank you, I am a beginner in unity, how can I check if the canvas is in Screen Space - Overlay?
Do you think that would fix the problem when flipping a page?
Thanks

**Comment by sebasgmas** [comment]
Ok, I checked the canvas and it is in screen space overlay, but it still dents work  properly when flipping page. Any suggestions?
Thanks a lot

**Comment by sebasgmas2705** [comment]
Ok i already fixed it. I forgot to assign the canvas I am working on on the inspector. 
Thanks a lot for you time
