### ISSUE TITLE
Clippingplane messed out

### ISSUE THREAD

**Issue by ilmatematico** [Dandarawy/Unity3DBookPageCurl#4]
I've got this strange behaviour on curl.
I'm using it with touchscript event system, replaced the Input.mouseposition in script to get true location with pointerpos

`private void pointersUpdatedHandler(object sender, PointerEventArgs e)
    {
        var pos = e.Pointers[0].Position;
        pointerpos = Camera.main.ScreenToWorldPoint(new Vector3(pos.x, pos.y, 0));
    }`

![image](https://cloud.githubusercontent.com/assets/6051870/23818108/93ace340-05f8-11e7-991d-071358aabd59.png)

is like the clipping plane position is messed up

**Comment by Dandarawy** [comment]
The Input.MousePosition is the mouse position in screen space, make sure to calculate the pointer position in screen space too, you should pass to this function the pointer position in screen space instead of mouse position
`DragRightPageToPoint(transformPoint(Input.mousePosition));`

**Comment by ilmatematico** [comment]
Yep, i've already done this, as you can see. The cornerpage is following correctly my pointer 
![image](https://cloud.githubusercontent.com/assets/6051870/23825033/add68b88-0682-11e7-8fb4-6941e1a754e6.png)

This is the code modifyied

[Book.cs.txt](https://github.com/Dandarawy/Unity3DBookPageCurl/files/835945/Book.cs.txt)

Righ now i've made a workaround as fitting the camera view to the touchscript input panel, it's working but is a temporary solution.

**Comment by Dandarawy** [comment]
OK, one more check, did you assign the Canvas reference in the book component ?!

**Comment by ilmatematico** [comment]
yes I assigned the parent canvas wich is in the previous screenshot "Screen Canvas" with this inspector data
![image](https://cloud.githubusercontent.com/assets/6051870/23827335/b56e818c-06b1-11e7-83ff-fd182dd4eb78.png)

I get better results Assigning the PointerVisualizer canvas, wich is a debug one for the touchscript input module

correctly grabbing the corner but same problem as above on masking

**Comment by Dandarawy** [comment]
Unfortunately this asset does not work with screenSpace-camera canvas , switch to ScreenSpace-Overlay.
I updated the pro version of this asset to work with screenSpace-camera with a very strict limitations on rotation, you can find it on asset store here https://www.assetstore.unity3d.com/#!/content/77222
