### ISSUE TITLE
Fliping pages on touch

### ISSUE THREAD

**Issue by LuoXiahong** [Dandarawy/Unity3DBookPageCurl#5]
When I'm trying to flip page on touch device the page animations is going to strange position and then is going back to touch position.

**Comment by LuoXiahong** [comment]
Ok I solved the problem -
Book.cs instead of line 109
`Vector3 point = Input.mousePosition`
		`if (Input.touchCount == 1) {`
			`point = new Vector3(Input.GetTouch (0).position.x,Input.GetTouch (0).position.y);`
		`}`
		`f= Vector3.Lerp(f,transformPoint( point), Time.deltaTime * 10);`

**Comment by sarathanjabam** [comment]
When i rotate the book , the positions of the pages are distorted while flipping the pages from left or from right

**Comment by Stigmamax** [comment]
it worked with 2 books in 2 different scenes. But suddenly, I can no longer turn the pages. It became inactive and I did not find why. Unity 5.6.2
