### ISSUE TITLE
Rotation  issue

### ISSUE THREAD

**Issue by pdivita** [Dandarawy/Unity3DBookPageCurl#6]
Hi,
I want to use the book in landscape mode, but simply rotating he book object doesn't work (curl effect is broken).
How can I rotate the book? Thanks!

**Comment by mdrunk** [comment]
I have the same problem.  The book doesn't work in any Z rotation but zero.

**Comment by Dandarawy** [comment]
I'm working on this issue and the fix will be pushed soon, maybe as a celebration of reaching 500 stars :D
