### ISSUE TITLE
Turning pages backwards shows the previous page

### ISSUE THREAD

**Issue by Esildor** [Dandarawy/Unity3DBookPageCurl#7]
**STR:**
1. Download and Import the 1.1 unitypackage
2. Open the _Assets\Book-Page Curl\Example\scenes\Example_1_Basic Book.unity_ example
3. Turn forward 2 pages
4. Turn back

**Expected Results:**
It visually looks like a book

**Actual Results:**
The second previous page floats above the first previous

**Editor:**
Unity 2019.1.4f1
Windows 10

**Notes:**
See this gif for a reference:

![bug](https://user-images.githubusercontent.com/5234969/61231566-5b946f00-a6fa-11e9-9ea2-4b3ce563d495.gif)

**Comment by Dandarawy** [comment]
Thanks for the bug report.
This issue has been noticed with unity 2019.1+
I couldn't figure out what causes this problem yet.
I strongly advice you to use unity 2018 if you want to use the free version of the asset, or to purchase the pro version if you want to work with unity 2019.
I'm working on this bug and hope I'll be able to fix it soon.

**Comment by Dandarawy** [comment]
This bug is in Unity2019.1 only, please consider using Unity2019.2 or any other unity version except unity 2019.1
Thanks
